// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package query_master

import (
	"time"
)

type ClientAuthToken struct {
	Token     string
	IpAddress string
	Expiry    time.Time
	CreatedAt time.Time
}

type ClientAuthTokenLog struct {
	Token     string
	IpAddress string
	UserAgent string
	CreatedAt time.Time
}

type Gateway struct {
	GatewayID string
	NodeID    string
	CreatedAt time.Time
}

type Node struct {
	NodeID       string
	PublicKey    string
	Region       string
	MaxCpu       int64
	MaxRam       int64
	AvailableCpu int64
	AvailableRam int64
	IpAddress    string
	Port         string
	CreatedAt    time.Time
	ModifiedAt   time.Time
}

type RegistryCredential struct {
	RegistryUrl string
	Username    string
	Password    string
	CreatedAt   time.Time
	ModifiedAt  interface{}
	ModifiedBy  string
}

type ResourceScaleEvent struct {
	ResourceID    string
	ResourceCount int64
	CreatedAt     time.Time
}

type Service struct {
	ServiceID      string
	MinInstances   int64
	MaxInstances   int64
	CpuPerInstance int64
	RamPerInstance int64
	Wasm           []byte
	CreatedAt      time.Time
	ModifiedAt     time.Time
}

type ServiceAccessRule struct {
	ServiceIDSource      string
	ServiceIDDestination string
}

type ServiceGateway struct {
	GatewayID string
	ServiceID string
	CreatedAt time.Time
}

type ServiceInstance struct {
	ServiceInstanceID string
	NodeID            string
	ServiceID         string
	CreatedAt         time.Time
}

type ServiceLoad struct {
	ServiceID         string
	ServiceInstanceID string
	Cpu               int64
	Ram               int64
	ClientCreatedAt   time.Time
	CreatedAt         time.Time
}

type ServiceScaleEvent struct {
	ServiceID     string
	InstanceCount int64
	CreatedAt     time.Time
}
